### ISSUE TITLE
Add proper support to any_interface triggers

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte-dashboard#14]
After https://github.com/astarte-platform/astarte/pull/187 gets merged. the dashboard should be adapted accordingly:
- `interface_name: *""` is valid only for `incoming_data` data triggers
- A trigger with `interface_name: "*"` doesn't require (_and doesn't send_) `interface_major`
- A trigger with `interface_name: "*"` must have match path `/*` and match operator `*` 

Note that the second item is already true in current Astarte version, which causes the dashboard to fail parsing any interface triggers since it doesn't find interface_major.

**Comment by Pavinati** [comment]
Fixed in #17
