### ISSUE TITLE
Filtering of results

### ISSUE THREAD

**Issue by AlessandroDon** [astarte-platform/astarte-dashboard#185]
Add a filter for selecting only a certain type of result: "connected", "never connected or "disconnected"

**Comment by Pavinati** [comment]
Thanks for opening this issue, we've started working on the feature.
Here are some screenshots of the work in progress feature

1) Unfiltered devices
![dashboard-unfiltered-devices](https://user-images.githubusercontent.com/5071605/94585193-f5a0f280-027f-11eb-9f6e-ca2f17a7b6c1.png)

2) Status filter applied
![dashboard-filtered-devices](https://user-images.githubusercontent.com/5071605/94585109-d6a26080-027f-11eb-8843-507290e898de.png)

3) Combine multiple filters
![dashboard-single-device](https://user-images.githubusercontent.com/5071605/94585225-005b8780-0280-11eb-9d9e-67a3d3e66c31.png)
