### ISSUE TITLE
Can't delete Trigger ending in whitespace

### ISSUE THREAD

**Issue by Annopaolo** [astarte-platform/astarte-dashboard#373]
When listing and displaying a Trigger having a name ending in whitespace, the dashboard correctly displays it. Indeed, the related HTTP request correctly encodes its name in the URL, e.g. `https://api.an.astarte.example/realmmanagement/v1/arealm/triggers/trigger%20name%20ends%20in%20whitespace%20`.
However, deletion fails with `"Trigger not found"` because the URL does not include the final whitespace `https://api.an.astarte.example/realmmanagement/v1/arealm/triggers/trigger%20name%20ends%20in%20whitespace`.

**Comment by davidebriani** [comment]
I am closing this issue since it's fixed in the v1.1 branch and the following versions.
